// Runs before dev, build and test. Keeps the website in step with the rest of the project:
//   schemas/*.schema.json  ->  src/data/generated/types.ts   (same shapes as the Python side)
//   config/spots.yaml      ->  src/data/generated/spots.json (names, positions and notes of the spots)
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { compile } from "json-schema-to-typescript";
import { parse } from "yaml";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..", "..");
const out = join(here, "..", "src", "data", "generated");
mkdirSync(out, { recursive: true });

const names = { conditions: "Conditions", river_flow: "RiverFlow", meta: "Meta", recommendations: "Recommendations" };
let types = "// GENERATED by scripts/prebuild.mjs from schemas/*.schema.json - do not edit.\n";
for (const [file, name] of Object.entries(names)) {
  const schema = JSON.parse(readFileSync(join(root, "schemas", `${file}.schema.json`), "utf8"));
  delete schema.title;
  delete schema.$id;
  types += "\n" + (await compile(schema, name, { bannerComment: "", additionalProperties: false, ignoreMinAndMaxItems: true }));
}
writeFileSync(join(out, "types.ts"), types);

const spots = parse(readFileSync(join(root, "config", "spots.yaml"), "utf8")).map((s) => ({
  id: s.id, name: s.name, lat: s.lat, lon: s.lon, notes: s.notes ?? "",
}));
writeFileSync(join(out, "spots.json"), JSON.stringify(spots, null, 2) + "\n");
console.log(`prebuild: types for ${Object.keys(names).length} schemas, ${spots.length} spots`);
